---
apiVersion: v1
kind: Deployment
metadata:
  name: pulp-content
  namespace: "{{ project_name }}"
  labels:
    app: pulp-content
spec:
  replicas: {{ pulp_content.replicas }}
  selector:
    matchLabels:
      app: pulp-content
  template:
    metadata:
      labels:
        app: pulp-content
    spec:
      #serviceAccountName: "{{ project_name }}-anyuid"
      volumes:
        - name: pulp-server
          configMap:
            name: pulp-server
            items:
              - path: settings.py
                key: settings.py
        - name: pulp-file-storage
          persistentVolumeClaim:
            claimName: pulp-file-storage
      containers:
        - name: pulp-content
          image: "{{ registry }}/{{ image }}:{{ version }}"
          command: ["pulp-content"]
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 24816
          volumeMounts:
            - name: pulp-server
              mountPath: "/etc/pulp/"
            - name: pulp-file-storage
              readOnly: false
              mountPath: "/var/lib/pulp"
