#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: pulp-fedora-box
#  namespace: pulp
#spec:
#  resources:
#    requests:
#      storage: 3Gi
#  accessModes:
#  - ReadWriteMany
---
### fedora
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pulp-fedora 
  namespace: rook-ceph
  labels:
    app: fedora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedora
  template:
    metadata:
      labels:
        app: fedora
    spec:
      volumes:
      - name: pulp-file-storage
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: pulp-file-storage
            clusterNamespace: rook-ceph
      containers:
        - name: fedora
          #image: docker.io/tchellomello/fedora:latest
          image: docker.io/fedora:latest
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
          volumeMounts:
            - name: pulp-file-storage
              mountPath: /var/lib/pulp
