---
- set_fact:
    secret_key: "{{ lookup('password', '/dev/null length=50 chars=ascii_letters') }}"

- name: pulp-content config-map
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.config-map.yaml') | from_yaml }}"
  with_items:
    - pulp-content

- name: pulp-content service
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.service.yaml') | from_yaml }}"
  with_items:
    - pulp-content

- name: pulp-content deployment
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.deployment.yaml') | from_yaml }}"
  with_items:
    - pulp-content
